# Laserwave theme for Kitty

background            #27212e
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #27212e
selection_background  #eb64b9
selection_foreground  #27212e

color0   #27212e
color8   #716385
color1   #eb64b9
color9   #eb64b9
color2   #74dfc4
color10  #74dfc4
color3   #ffe261
color11  #ffe261
color4   #40b4c4
color12  #40b4c4
color5   #b381c5
color13  #b381c5
color6   #afbfcb
color14  #afbfcb
color7   #ffffff
color15  #ffffff
