# vim:ft=kitty

## name: White Sand
## author: Ported from mswift42/white-sand-theme (Emacs)
## blurb: A warm light theme based on the White Sand Emacs theme

background                #fcfcfc
foreground                #585858

selection_background      #dfd6cd
selection_foreground      #585858

url_color                 #1a8591

wayland_titlebar_color    system
macos_titlebar_color      system

cursor                    #585858
cursor_text_color         #f5ebe1

active_border_color       #b4ada6
inactive_border_color     #dfd6cd
bell_border_color         #b3534b
visual_bell_color         none

active_tab_background     #f5ebe1
active_tab_foreground     #585858
inactive_tab_background   #dfd6cd
inactive_tab_foreground   #7d7d7d
tab_bar_background        none
tab_bar_margin_color      none

# normal
color0                    #585858
color1                    #b3534b
color2                    #476238
color3                    #697024
color4                    #4a858c
color5                    #8c4a79
color6                    #1a8591
color7                    #dfd6cd

# bright
color8                    #a9a9a9
color9                    #bd745e
color10                   #5f9298
color11                   #ca881d
color12                   #43757c
color13                   #ff1276
color14                   #5f9298
color15                   #f5ebe1
