cursor #1b1b1b
cursor_text_color #474747

foreground            #1b1b1b
background            #f9f9f9
selection_foreground  #ffffff
selection_background  #b0cccc
url_color             #00696c

color0   #131313
color1   #79002b
color2   #005f08
color3   #998d00
color4   #006e71
color5   #81bdbf
color6   #00696c
color7   #202323
color8   #666c6c
color9   #c63c58
color10  #008c0b
color11  #a59900
color12  #0b7c80
color13  #81bdbf
color14  #468a8c
color15  #b7bfbf
