# Allow text selection in terminal apps.
mouse_map left press ungrabbed,grabbed mouse_selection normal
mouse_map left doublepress ungrabbed,grabbed mouse_selection word
mouse_map left triplepress ungrabbed,grabbed mouse_selection line

map ctrl+c copy_and_clear_or_interrupt
map ctrl+shift+c copy_to_clipboard
